name: FinanceMonitor

packages:
    CMExtensions:
        github: mkrisztian95/CMExtensions
        branch: main
    Depin:
        github: KOMA-Inc/Depin
        from: 3.0.0
    XCoordinator:
        github: QuickBirdEng/XCoordinator
        from: 2.0.0
    Lottie:
        github: airbnb/lottie-ios.git
        from: 3.0.0
    # for testing
    Quick:
        github: Quick/Quick
        from: 6.0.0
    Nimble:
        github: Quick/Nimble
        from: 11.0.0
    Spry:
        github: mkrisztian95/Spry
        branch: master

options:
    createItermediateGroups: true
    useBaseInternationalization: false

settings:
    base:
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: NO
        IPHONEOS_DEPLOYMENT_TARGET: 15.0

fileGroups:
    - project.yml
    - .swiftlint.yml

configFiles:
    Debug: Configs/Project-Debug.xcconfig
    Release: Configs/Project-Release.xcconfig


targets:
    FinanceMonitor:
        configFiles:
            Debug: Configs/FinanceMonitor/Debug.xcconfig
            Release: Configs/FinanceMonitor/Release.xcconfig
        dependencies:
        - package:  XCoordinator
        - package:  Depin
        - package: CMExtensions
          product: FoundationPlus
        - package: CMExtensions
          product: UIKitPlus
        - package: CMExtensions
          product: CombinePlus
        - package: CMExtensions
          product: AVFoundationPlus
        - package: Lottie
        platform: iOS

        postCompileScripts:

        -   name: Swiftlint
            script: |
                # Type a script or drag a script file from your workspace to insert its path.
                export PATH="$PATH:/opt/homebrew/bin"
                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
            basedOnDependencyAnalysis: false

        sources:
        -   FinanceMonitor
        -   Configs
        type: application
    FinanceMonitorTests:
        dependencies:
        -   package: Quick
        -   package: Nimble
        -   package: Spry
        -   target: FinanceMonitor
        platform: iOS
        settings:
            base:
                BUNDLE_LOADER: $(TEST_HOST)
                GENERATE_INFOPLIST_FILE: YES
                TEST_HOST: $(BUILT_PRODUCTS_DIR)/FinanceMonitor.app/FinanceMonitor
                INFOPLIST_FILE: FinanceMonitorTests/Info.plist
        sources:
        -   FinanceMonitorTests
        type: bundle.unit-test

schemes:
    FinanceMonitor:
        build:
            targets:
                FinanceMonitor: all
    FinanceMonitorTests:
        build:
            targets:
                FinanceMonitorTests: [test, run]
        test:
            targets:
                - name: FinanceMonitorTests
            testPlans:
                - path: FinanceMonitor/FinanceMonitorTests.xctestplan
